services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: gateway
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway"]
      interval: 5s
      timeout: 3s
      retries: 20

  mockboard:
    build:
      context: .
      dockerfile: src/MockBoard.Adapter/Dockerfile
    ports: ["8081:8081"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 20

  gateway:
    build:
      context: .
      dockerfile: src/Gateway.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      mockboard:
        condition: service_healthy
    environment:
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=gateway;Username=gateway;Password=devpass
      ASPNETCORE_ENVIRONMENT: Development
      MOCKBOARD_URL: http://mockboard:8081
    ports: ["8080:8080"]
    volumes:
      - gateway_dataprotection:/app/dataprotection



volumes:
  gateway_dataprotection:

